### ISSUE TITLE
API to convert ZIP to Coordinates

### ISSUE THREAD

**Issue by eamahma** [mels065/move-towards-the-movies#3]
Use the MapBox API to turn the local Zip Code to latitude and longitude coordinates.

**Comment by mels065** [comment]
https://www.mapbox.com/

**Comment by eamahma** [comment]
https://www.zipcodeapi.com/API

**Comment by eamahma** [comment]
I tried to pass value from another file to:
getCoordinatesFromZipCode(zip)
    .then((coords) => {
        console.log(coords);
    });

it says zip is not defined; how we use and define external variables?

**Comment by Bluekev22** [comment]
I believe you have to store the value of the form that’s been submitted into a variable and then call that function with the variable passed as the argument. Or I would think.. I’m still learning lol


Sent from Yahoo Mail for iPhone


On Wednesday, July 7, 2021, 8:58 PM, eamahma ***@***.***> wrote:




I tried to pass value from another file to:
getCoordinatesFromZipCode(zip)
.then((coords) => {
console.log(coords);
});

it says zip is not defined; how we use and define external variables?
